# Generated by Django 5.0.6 on 2025-11-07 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_specialization_slug'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField(help_text='Estimated duration of the surgery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Surgery Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surgeries', to=settings.AUTH_USER_MODEL)),
                ('operation_theater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation_theater.operationtheater')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='doctors.doctor')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation_theater.surgerytype')),
            ],
            options={
                'verbose_name_plural': 'Surgeries',
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='operation_theater.surgery')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('surgeon', 'Surgeon'), ('assistant', 'Assistant Surgeon'), ('anesthetist', 'Anesthetist'), ('nurse', 'Scrub Nurse'), ('technician', 'Surgical Technician'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary surgeon for the procedure')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_teams', to='doctors.doctor')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='operation_theater.surgery')),
            ],
            options={
                'verbose_name_plural': 'Surgery Teams',
                'ordering': ['-is_primary', 'role', 'doctor__user__first_name'],
                'unique_together': {('surgery', 'doctor')},
            },
        ),
    ]
