# Generated by Django 5.0.6 on 2025-11-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_specialization_slug'),
        ('operation_theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtheater',
            name='supervising_doctors',
            field=models.ManyToManyField(blank=True, help_text='Doctors who supervise this operation theater.', related_name='supervised_operation_theaters', to='doctors.doctor'),
        ),
    ]
