# Generated by Django 5.0.6 on 2025-11-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_theater', '0002_operationtheater_supervising_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='surgery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation_theater.surgerytype'),
        ),
    ]
