# Generated by Django 5.0.6 on 2025-11-06 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_specialization_slug'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='tablet', max_length=50)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='e.g., 1 tablet, 5ml, etc.', max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once Daily'), ('BID', 'Twice Daily'), ('TID', 'Three Times Daily'), ('QID', 'Four Times Daily'), ('QHS', 'At Bedtime'), ('Q4H', 'Every 4 Hours'), ('Q6H', 'Every 6 Hours'), ('Q8H', 'Every 8 Hours'), ('PRN', 'As Needed')], max_length=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration of treatment')),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('indefinite', 'Until Further Notice')], default='days', max_length=10)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions', null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicines', to='doctors.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_prescriptions', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once Daily'), ('BID', 'Twice Daily'), ('TID', 'Three Times Daily'), ('QID', 'Four Times Daily'), ('QHS', 'At Bedtime'), ('Q4H', 'Every 4 Hours'), ('Q6H', 'Every 6 Hours'), ('Q8H', 'Every 8 Hours'), ('PRN', 'As Needed')], max_length=10)),
                ('duration', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('indefinite', 'Until Further Notice')], max_length=10)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units to dispense')),
                ('refill_allowed', models.BooleanField(default=False)),
                ('refill_times', models.PositiveIntegerField(default=0, help_text='Number of refills allowed')),
                ('notes', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
        ),
    ]
