# Generated by Django 5.0.6 on 2025-11-08 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_address_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('registration', 'Registration Fee'), ('consultation', 'Consultation Fee'), ('procedure', 'Procedure Fee'), ('medication', 'Medication'), ('other', 'Other')], default='registration', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('insurance', 'Insurance')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'patient payment',
                'verbose_name_plural': 'patient payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
