# Generated by Django 5.0.6 on 2025-11-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
