# Generated by Django 5.0.6 on 2025-11-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpayment',
            name='payment_type',
            field=models.CharField(choices=[('registration', 'Registration Fee'), ('consultation', 'Consultation Fee'), ('procedure', 'Procedure Fee'), ('medication', 'Medication'), ('discharge', 'Discharge Payment'), ('bill_payment', 'Bill Payment'), ('other', 'Other')], default='registration', max_length=20),
        ),
    ]
